# Site settings
title: Student Portfolios | BDes (Hons) Interaction Design
email: tajdidrahman@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A list of portfolios from students studying BDes (Hons) Interaction Design.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
